#!/bin/bash
#═══════════════════════════════════════════════════════════════════════════════
# UNIVERSAL MEMORY OPTIMIZER v1.0.0
#
# Cross-distribution Linux memory optimizer with ZRAM + Disk Swap
# Architecture: ZRAM = RAM/2, Swapfile = ZRAM/2 (RAM/4)
#
# Supports: Fedora, RHEL, Debian, Ubuntu, Arch, openSUSE
# Bootloaders: GRUB, systemd-boot, UKI
# Filesystems: ext4, xfs, btrfs
#
# Features combined from:
#   - fedora-memory-optimizer (Generic v4) - Bootloader detection, hibernate protection
#   - lunar-lake-32gb-optimizer (v4) - Rollback, verification, strict mode
#
# Best Practices Sources (2025-2026):
#   - ArchWiki ZRAM: https://wiki.archlinux.org/title/Zram
#   - Kernel Documentation: https://docs.kernel.org/admin-guide/sysctl/vm.html
#   - Fedora Changes: https://fedoraproject.org/wiki/Changes/SwapOnZRAM
#   - systemd-oomd: https://www.phoronix.com/news/Systemd-Facebook-OOMD
#
# Author: Generated by Claude (Anthropic)
# License: MIT
#═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail
IFS=$'\n\t'

#───────────────────────────────────────────────────────────────────────────────
# CONSTANTS
#───────────────────────────────────────────────────────────────────────────────

readonly SCRIPT_VERSION="1.0.0"
readonly SCRIPT_NAME="universal-memory-optimizer"
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly CYAN='\033[0;36m'
readonly MAGENTA='\033[0;35m'
readonly BOLD='\033[1m'
readonly NC='\033[0m'

# Architecture: ZRAM = RAM/2, Swapfile = RAM (1:1)
# Configurable ratios for different use cases
readonly ZRAM_RATIO=50        # 50% of RAM
readonly SWAPFILE_RATIO=100   # 100% of RAM (1:1 ratio, hibernate-ready)

# Swap priorities (higher = used first)
readonly ZRAM_PRIORITY=100    # ZRAM: fast, compressed
readonly SWAPFILE_PRIORITY=30 # Disk: slower, for overflow

# Sysctl values (Best Practices 2025-2026)
readonly SYSCTL_SWAPPINESS=180
readonly SYSCTL_PAGE_CLUSTER=0
readonly SYSCTL_VFS_CACHE_PRESSURE=50
readonly SYSCTL_WATERMARK_SCALE_FACTOR=125
readonly SYSCTL_WATERMARK_BOOST_FACTOR=0
readonly SYSCTL_DIRTY_RATIO=10
readonly SYSCTL_DIRTY_BACKGROUND_RATIO=5

# Compression algorithm
readonly ZRAM_ALGORITHM="zstd"

# File paths
readonly SYSCTL_CONF="/etc/sysctl.d/99-memory-optimizer.conf"
readonly ZRAM_CONF="/etc/systemd/zram-generator.conf"
readonly SWAPFILE_PATH="/swapfile"
readonly BACKUP_BASE="/root/memory-optimizer-backups"
readonly REPORT_DIR="/root/memory-optimizer-reports"
readonly VERIFY_SCRIPT="/usr/local/bin/memory-optimizer-verify"

#───────────────────────────────────────────────────────────────────────────────
# GLOBAL STATE
#───────────────────────────────────────────────────────────────────────────────

# System info (populated by detect_system)
DISTRO=""
DISTRO_FAMILY=""
DISTRO_VERSION=""
TOTAL_RAM_KB=0
TOTAL_RAM_GB=0
ZRAM_SIZE_GB=0
SWAPFILE_SIZE_GB=0
ROOT_FS_TYPE=""
INIT_SYSTEM=""

# Bootloader info (populated by detect_bootloader)
DETECTED_BOOTLOADER=""
BOOTLOADER_CONFIDENCE=""
BOOTLOADER_EVIDENCE=""

# Hibernate info (populated by check_hibernate)
HIBERNATE_STATUS="NOT_CHECKED"
HIBERNATE_SWAPFILE_SIZE=0

# Runtime flags
DRY_RUN=false
FORCE_MODE=false
VERBOSE=false
SKIP_CONFIRMATION=false
# Backup tracking
CURRENT_BACKUP_DIR=""

# Anomaly tracking
declare -a ANOMALIES=()
declare -a WARNINGS=()
declare -a SUCCESSES=()

#───────────────────────────────────────────────────────────────────────────────
# LOGGING FUNCTIONS
#───────────────────────────────────────────────────────────────────────────────

log_info() {
    echo -e "${BLUE}[INFO]${NC} $*"
}

log_success() {
    echo -e "${GREEN}[OK]${NC} $*"
    SUCCESSES+=("$*")
}

log_warning() {
    echo -e "${YELLOW}[WARN]${NC} $*"
    WARNINGS+=("$*")
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

log_debug() {
    [[ "$VERBOSE" == "true" ]] && echo -e "${MAGENTA}[DEBUG]${NC} $*" || true
}

log_header() {
    echo ""
    echo -e "${CYAN}═══════════════════════════════════════════════════════════════════════${NC}"
    echo -e "${BOLD} $*${NC}"
    echo -e "${CYAN}═══════════════════════════════════════════════════════════════════════${NC}"
}

log_subheader() {
    echo ""
    echo -e "${CYAN}─── $* ───${NC}"
}

add_anomaly() {
    local severity="$1"
    local category="$2"
    local expected="$3"
    local actual="$4"
    local impact="$5"
    local suggestion="$6"

    local anomaly_json=$(cat <<EOF
{
    "severity": "$severity",
    "category": "$category",
    "expected": "$expected",
    "actual": "$actual",
    "impact": "$impact",
    "suggestion": "$suggestion",
    "timestamp": "$(date -Iseconds)"
}
EOF
)
    ANOMALIES+=("$anomaly_json")

    case "$severity" in
        CRITICAL) log_error "ANOMALY: $category - $impact" ;;
        WARNING)  log_warning "ANOMALY: $category - $impact" ;;
        *)        log_info "ANOMALY: $category - $impact" ;;
    esac
}

#───────────────────────────────────────────────────────────────────────────────
# SYSTEM DETECTION
#───────────────────────────────────────────────────────────────────────────────

detect_system() {
    log_subheader "Detecting System Configuration"

    # RAM detection
    TOTAL_RAM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
    TOTAL_RAM_GB=$((TOTAL_RAM_KB / 1024 / 1024))

    # Handle edge case for systems with less than 1GB
    [[ $TOTAL_RAM_GB -lt 1 ]] && TOTAL_RAM_GB=1

    # Calculate sizes based on configurable ratios
    # ZRAM = RAM * ZRAM_RATIO / 100
    ZRAM_SIZE_GB=$((TOTAL_RAM_GB * ZRAM_RATIO / 100))
    [[ $ZRAM_SIZE_GB -lt 1 ]] && ZRAM_SIZE_GB=1

    # Swapfile = RAM * SWAPFILE_RATIO / 100
    SWAPFILE_SIZE_GB=$((TOTAL_RAM_GB * SWAPFILE_RATIO / 100))
    [[ $SWAPFILE_SIZE_GB -lt 1 ]] && SWAPFILE_SIZE_GB=1

    log_info "RAM: ${TOTAL_RAM_GB}GB"
    log_info "ZRAM Size: ${ZRAM_SIZE_GB}GB (${ZRAM_RATIO}% of RAM)"
    log_info "Swapfile Size: ${SWAPFILE_SIZE_GB}GB (${SWAPFILE_RATIO}% of RAM)"

    # Distribution detection
    if [[ -f /etc/os-release ]]; then
        source /etc/os-release
        DISTRO="${ID:-unknown}"
        DISTRO_VERSION="${VERSION_ID:-unknown}"

        case "$DISTRO" in
            fedora|rhel|centos|rocky|alma|oracle)
                DISTRO_FAMILY="redhat"
                ;;
            debian|ubuntu|linuxmint|pop|elementary|zorin)
                DISTRO_FAMILY="debian"
                ;;
            arch|manjaro|endeavouros|garuda)
                DISTRO_FAMILY="arch"
                ;;
            opensuse*|suse*)
                DISTRO_FAMILY="suse"
                ;;
            *)
                DISTRO_FAMILY="unknown"
                ;;
        esac
    else
        DISTRO="unknown"
        DISTRO_FAMILY="unknown"
        DISTRO_VERSION="unknown"
    fi

    log_info "Distribution: $DISTRO ($DISTRO_FAMILY) v$DISTRO_VERSION"

    # Root filesystem type
    ROOT_FS_TYPE=$(df -T / | awk 'NR==2 {print $2}')
    log_info "Root Filesystem: $ROOT_FS_TYPE"

    # Init system
    if [[ -d /run/systemd/system ]]; then
        INIT_SYSTEM="systemd"
    elif [[ -f /sbin/openrc ]]; then
        INIT_SYSTEM="openrc"
    else
        INIT_SYSTEM="unknown"
    fi

    log_info "Init System: $INIT_SYSTEM"

    # Verify systemd (required for zram-generator)
    if [[ "$INIT_SYSTEM" != "systemd" ]]; then
        add_anomaly "CRITICAL" "init_system" "systemd" "$INIT_SYSTEM" \
            "zram-generator requires systemd" \
            "This optimizer requires systemd. Consider manual ZRAM setup."
        return 1
    fi

    return 0
}

#───────────────────────────────────────────────────────────────────────────────
# BOOTLOADER DETECTION (Evidence-Based Scoring)
#───────────────────────────────────────────────────────────────────────────────

detect_bootloader() {
    log_subheader "Detecting Bootloader"

    local grub_score=0
    local systemd_boot_score=0
    local uki_score=0
    BOOTLOADER_EVIDENCE=""

    # Evidence 1: /etc/default/grub
    if [[ -f /etc/default/grub ]]; then
        ((grub_score += 30))
        BOOTLOADER_EVIDENCE+="[GRUB+30] /etc/default/grub exists\n"
    fi

    # Evidence 2: /boot/grub2 or /boot/grub
    if [[ -d /boot/grub2 ]] || [[ -d /boot/grub ]]; then
        ((grub_score += 25))
        BOOTLOADER_EVIDENCE+="[GRUB+25] /boot/grub{2} directory exists\n"
    fi

    # Evidence 3: grubby command
    if command -v grubby &>/dev/null; then
        ((grub_score += 15))
        BOOTLOADER_EVIDENCE+="[GRUB+15] grubby command available\n"
    fi

    # Evidence 4: /boot/loader/entries (systemd-boot)
    if [[ -d /boot/loader/entries ]]; then
        ((systemd_boot_score += 40))
        BOOTLOADER_EVIDENCE+="[systemd-boot+40] /boot/loader/entries exists\n"
    fi

    # Evidence 5: bootctl installed
    if command -v bootctl &>/dev/null; then
        if bootctl is-installed &>/dev/null 2>&1; then
            ((systemd_boot_score += 35))
            BOOTLOADER_EVIDENCE+="[systemd-boot+35] bootctl reports installed\n"
        fi
    fi

    # Evidence 6: UKI layout
    if [[ -f /etc/kernel/install.conf ]]; then
        if grep -q "layout=uki" /etc/kernel/install.conf 2>/dev/null; then
            ((uki_score += 50))
            BOOTLOADER_EVIDENCE+="[UKI+50] layout=uki in install.conf\n"
        fi
    fi

    # Evidence 7: EFI binaries
    if [[ -d /sys/firmware/efi ]]; then
        if [[ -f /boot/efi/EFI/fedora/shimx64.efi ]] || \
           [[ -f /boot/efi/EFI/ubuntu/shimx64.efi ]] || \
           [[ -f /boot/efi/EFI/debian/shimx64.efi ]]; then
            ((grub_score += 10))
            BOOTLOADER_EVIDENCE+="[GRUB+10] Shim found in EFI\n"
        fi
        if [[ -f /boot/efi/EFI/systemd/systemd-bootx64.efi ]]; then
            ((systemd_boot_score += 20))
            BOOTLOADER_EVIDENCE+="[systemd-boot+20] systemd-boot EFI binary\n"
        fi
    fi

    # Determine winner
    local max_score=$grub_score
    DETECTED_BOOTLOADER="grub"

    if [[ $systemd_boot_score -gt $max_score ]]; then
        max_score=$systemd_boot_score
        DETECTED_BOOTLOADER="systemd-boot"
    fi

    if [[ $uki_score -gt $max_score ]]; then
        max_score=$uki_score
        DETECTED_BOOTLOADER="uki"
    fi

    # Confidence level
    if [[ $max_score -ge 50 ]]; then
        BOOTLOADER_CONFIDENCE="HIGH"
    elif [[ $max_score -ge 30 ]]; then
        BOOTLOADER_CONFIDENCE="MEDIUM"
    elif [[ $max_score -ge 15 ]]; then
        BOOTLOADER_CONFIDENCE="LOW"
    else
        BOOTLOADER_CONFIDENCE="NONE"
        DETECTED_BOOTLOADER="unknown"
    fi

    log_info "Bootloader: $DETECTED_BOOTLOADER (Confidence: $BOOTLOADER_CONFIDENCE, Score: $max_score)"

    if [[ "$VERBOSE" == "true" ]]; then
        echo -e "$BOOTLOADER_EVIDENCE"
    fi

    [[ "$BOOTLOADER_CONFIDENCE" == "HIGH" ]] || [[ "$BOOTLOADER_CONFIDENCE" == "MEDIUM" ]]
}

#───────────────────────────────────────────────────────────────────────────────
# HIBERNATE DETECTION
#───────────────────────────────────────────────────────────────────────────────

check_hibernate() {
    log_subheader "Checking Hibernate Configuration"

    HIBERNATE_STATUS="NOT_CONFIGURED"

    # Check kernel cmdline for resume parameter
    if grep -q "resume=" /proc/cmdline; then
        HIBERNATE_STATUS="KERNEL_RESUME_SET"
        log_info "Kernel resume parameter detected"

        # Check if current swapfile is hibernate swapfile
        if [[ -f "$SWAPFILE_PATH" ]]; then
            local swap_bytes=$(stat -c%s "$SWAPFILE_PATH" 2>/dev/null || echo 0)
            local swap_gb=$((swap_bytes / 1024 / 1024 / 1024))
            HIBERNATE_SWAPFILE_SIZE=$swap_gb

            # Hibernate swapfile should be at least RAM size
            if [[ $swap_gb -ge $TOTAL_RAM_GB ]]; then
                HIBERNATE_STATUS="CONFIGURED"
                log_warning "Hibernate swapfile detected: ${swap_gb}GB (>= ${TOTAL_RAM_GB}GB RAM)"
                log_warning "Modifying $SWAPFILE_PATH may break hibernate!"
            fi
        fi
    fi

    # Check fstab for resume
    if grep -q "resume" /etc/fstab 2>/dev/null; then
        [[ "$HIBERNATE_STATUS" == "NOT_CONFIGURED" ]] && HIBERNATE_STATUS="FSTAB_RESUME_SET"
        log_info "Resume entry found in fstab"
    fi

    # Check dracut resume module
    if [[ -f /etc/dracut.conf.d/resume.conf ]]; then
        [[ "$HIBERNATE_STATUS" == "NOT_CONFIGURED" ]] && HIBERNATE_STATUS="DRACUT_CONFIGURED"
        log_info "Dracut resume configuration found"
    fi

    if [[ "$HIBERNATE_STATUS" == "NOT_CONFIGURED" ]]; then
        log_success "No hibernate configuration detected"
    fi

    [[ "$HIBERNATE_STATUS" == "CONFIGURED" ]]
}

#───────────────────────────────────────────────────────────────────────────────
# PRE-FLIGHT CHECKS
#───────────────────────────────────────────────────────────────────────────────

preflight_checks() {
    log_header "Pre-flight Checks"

    local checks_passed=0
    local checks_total=10

    # Check 1: Root privileges
    log_info "1/10: Checking root privileges..."
    if [[ $EUID -eq 0 ]]; then
        log_success "Running as root"
        ((checks_passed++))
    else
        log_error "Root privileges required"
        return 1
    fi

    # Check 2: Systemd
    log_info "2/10: Checking init system..."
    if [[ "$INIT_SYSTEM" == "systemd" ]]; then
        log_success "Systemd detected"
        ((checks_passed++))
    else
        log_error "Systemd required for zram-generator"
        return 1
    fi

    # Check 3: Kernel version (>= 5.0 for btrfs swapfile)
    log_info "3/10: Checking kernel version..."
    local kernel_version=$(uname -r | cut -d. -f1-2)
    local kernel_major=$(echo "$kernel_version" | cut -d. -f1)
    if [[ $kernel_major -ge 5 ]]; then
        log_success "Kernel $kernel_version (>= 5.0)"
        ((checks_passed++))
    else
        log_warning "Kernel $kernel_version may have limited features"
        ((checks_passed++))  # Non-fatal
    fi

    # Check 4: zram-generator availability
    log_info "4/10: Checking zram-generator..."
    if [[ -f /usr/lib/systemd/system-generators/zram-generator ]] || \
       command -v zram-generator &>/dev/null; then
        log_success "zram-generator available"
        ((checks_passed++))
    else
        log_warning "zram-generator not found - will attempt installation"
        ((checks_passed++))  # Will handle later
    fi

    # Check 5: Disk space for swapfile
    log_info "5/10: Checking disk space..."
    local available_gb=$(df -BG / | awk 'NR==2 {gsub(/G/,""); print $4}')
    local required_gb=$((SWAPFILE_SIZE_GB + 5))  # +5GB margin
    if [[ $available_gb -ge $required_gb ]]; then
        log_success "Disk space: ${available_gb}GB available (need ${required_gb}GB)"
        ((checks_passed++))
    else
        add_anomaly "CRITICAL" "disk_space" "${required_gb}GB" "${available_gb}GB" \
            "Insufficient disk space for swapfile" \
            "Free up disk space or reduce swapfile size"
        log_error "Insufficient disk space: ${available_gb}GB < ${required_gb}GB"
        return 1
    fi

    # Check 6: Bootloader detection
    log_info "6/10: Checking bootloader..."
    if detect_bootloader; then
        ((checks_passed++))
    else
        log_warning "Bootloader detection confidence is low"
        ((checks_passed++))  # Non-fatal but will warn
    fi

    # Check 7: Existing ZRAM
    log_info "7/10: Checking existing ZRAM..."
    if [[ -b /dev/zram0 ]]; then
        local zram_size=$(cat /sys/block/zram0/disksize 2>/dev/null || echo 0)
        local zram_size_gb=$((zram_size / 1024 / 1024 / 1024))
        log_info "Existing ZRAM: ${zram_size_gb}GB (will be reconfigured)"
    else
        log_info "No existing ZRAM"
    fi
    ((checks_passed++))

    # Check 8: ZSWAP status
    log_info "8/10: Checking ZSWAP..."
    if [[ -f /sys/module/zswap/parameters/enabled ]]; then
        local zswap_enabled=$(cat /sys/module/zswap/parameters/enabled)
        if [[ "$zswap_enabled" == "Y" ]] || [[ "$zswap_enabled" == "1" ]]; then
            log_warning "ZSWAP is enabled - will be disabled for ZRAM"
        else
            log_success "ZSWAP is already disabled"
        fi
    else
        log_success "ZSWAP module not loaded"
    fi
    ((checks_passed++))

    # Check 9: Hibernate configuration
    log_info "9/10: Checking hibernate..."
    if check_hibernate; then
        if [[ "$FORCE_MODE" != "true" ]]; then
            log_warning "Hibernate configured - swapfile will be preserved"
        else
            log_warning "FORCE mode: Will modify despite hibernate config"
        fi
    fi
    ((checks_passed++))

    # Check 10: Required commands
    log_info "10/10: Checking required commands..."
    local missing_cmds=()
    for cmd in mkswap swapon swapoff systemctl; do
        if ! command -v "$cmd" &>/dev/null; then
            missing_cmds+=("$cmd")
        fi
    done

    if [[ ${#missing_cmds[@]} -eq 0 ]]; then
        log_success "All required commands available"
        ((checks_passed++))
    else
        log_error "Missing commands: ${missing_cmds[*]}"
        return 1
    fi

    # Summary
    echo ""
    log_info "Pre-flight checks: $checks_passed/$checks_total passed"

    if [[ $checks_passed -lt $checks_total ]]; then
        log_warning "Some checks had warnings - review before proceeding"
    fi

    return 0
}

#───────────────────────────────────────────────────────────────────────────────
# BACKUP SYSTEM
#───────────────────────────────────────────────────────────────────────────────

create_backup() {
    log_subheader "Creating Backup"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would create backup at $BACKUP_BASE/backup-YYYYMMDD-HHMMSS"
        CURRENT_BACKUP_DIR="(dry-run)"
        return 0
    fi

    CURRENT_BACKUP_DIR="$BACKUP_BASE/backup-$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$CURRENT_BACKUP_DIR"

    # Create manifest
    cat > "$CURRENT_BACKUP_DIR/MANIFEST.json" << EOF
{
    "version": "$SCRIPT_VERSION",
    "created": "$(date -Iseconds)",
    "hostname": "$(hostname)",
    "kernel": "$(uname -r)",
    "distro": "$DISTRO",
    "distro_version": "$DISTRO_VERSION",
    "ram_gb": $TOTAL_RAM_GB,
    "zram_size_gb": $ZRAM_SIZE_GB,
    "swapfile_size_gb": $SWAPFILE_SIZE_GB,
    "bootloader": "$DETECTED_BOOTLOADER",
    "files": []
}
EOF

    local files_backed_up=()

    # Backup existing configs
    local files_to_backup=(
        "$SYSCTL_CONF"
        "$ZRAM_CONF"
        "/etc/fstab"
    )

    for file in "${files_to_backup[@]}"; do
        if [[ -f "$file" ]]; then
            local dest_dir="$CURRENT_BACKUP_DIR$(dirname "$file")"
            mkdir -p "$dest_dir"
            cp "$file" "$dest_dir/"
            files_backed_up+=("$file")
            log_debug "Backed up: $file"
        fi
    done

    # Save current sysctl values
    cat > "$CURRENT_BACKUP_DIR/sysctl-snapshot.txt" << EOF
# Sysctl values at backup time: $(date -Iseconds)
vm.swappiness = $(cat /proc/sys/vm/swappiness)
vm.page-cluster = $(cat /proc/sys/vm/page_cluster 2>/dev/null || echo "N/A")
vm.vfs_cache_pressure = $(cat /proc/sys/vm/vfs_cache_pressure)
vm.watermark_scale_factor = $(cat /proc/sys/vm/watermark_scale_factor)
vm.dirty_ratio = $(cat /proc/sys/vm/dirty_ratio)
vm.dirty_background_ratio = $(cat /proc/sys/vm/dirty_background_ratio)
EOF

    # Save current swap status
    swapon --show > "$CURRENT_BACKUP_DIR/swap-status.txt" 2>/dev/null || true
    zramctl > "$CURRENT_BACKUP_DIR/zram-status.txt" 2>/dev/null || true

    log_success "Backup created: $CURRENT_BACKUP_DIR"
    log_info "Files backed up: ${#files_backed_up[@]}"

    echo "$CURRENT_BACKUP_DIR"
}

#───────────────────────────────────────────────────────────────────────────────
# ROLLBACK SYSTEM
#───────────────────────────────────────────────────────────────────────────────

list_backups() {
    echo ""
    echo -e "${BOLD}Available Backups:${NC}"
    echo ""

    local count=0
    for dir in "$BACKUP_BASE"/backup-*; do
        if [[ -d "$dir" ]]; then
            ((count++))
            local manifest="$dir/MANIFEST.json"

            echo -e "  ${GREEN}$count)${NC} $dir"

            if [[ -f "$manifest" ]]; then
                local created=$(grep '"created"' "$manifest" | cut -d'"' -f4)
                local kernel=$(grep '"kernel"' "$manifest" | cut -d'"' -f4)
                echo "     Created: $created"
                echo "     Kernel: $kernel"
            fi
            echo ""
        fi
    done

    if [[ $count -eq 0 ]]; then
        echo -e "  ${YELLOW}No backups found.${NC}"
    fi
    echo ""
}

rollback() {
    local backup_dir="$1"

    if [[ -z "$backup_dir" ]]; then
        log_error "No backup directory specified"
        echo ""
        echo "Usage: $0 --rollback <backup_directory>"
        list_backups
        return 1
    fi

    if [[ ! -d "$backup_dir" ]]; then
        log_error "Backup directory not found: $backup_dir"
        list_backups
        return 1
    fi

    log_header "Rollback to: $backup_dir"

    # Show what will be restored
    echo ""
    echo -e "${BOLD}Files to restore:${NC}"
    find "$backup_dir" -type f -name "*.conf" -o -name "fstab" | while read -r file; do
        local relative="${file#$backup_dir}"
        echo "  - $relative"
    done
    echo ""

    if [[ "$SKIP_CONFIRMATION" != "true" ]]; then
        read -r -p "Proceed with rollback? (y/N) " response
        if [[ ! "$response" =~ ^[Yy] ]]; then
            log_info "Rollback cancelled"
            return 0
        fi
    fi

    local restored=0
    local failed=0

    # Restore configs
    if [[ -f "$backup_dir$SYSCTL_CONF" ]]; then
        cp "$backup_dir$SYSCTL_CONF" "$SYSCTL_CONF" && ((restored++)) || ((failed++))
    else
        rm -f "$SYSCTL_CONF"
    fi

    if [[ -f "$backup_dir$ZRAM_CONF" ]]; then
        cp "$backup_dir$ZRAM_CONF" "$ZRAM_CONF" && ((restored++)) || ((failed++))
    else
        rm -f "$ZRAM_CONF"
    fi

    if [[ -f "$backup_dir/etc/fstab" ]]; then
        cp /etc/fstab /etc/fstab.pre-rollback.$(date +%Y%m%d%H%M%S)
        cp "$backup_dir/etc/fstab" /etc/fstab && ((restored++)) || ((failed++))
    fi

    # Apply changes
    sysctl --system > /dev/null 2>&1 || true
    systemctl daemon-reload

    echo ""
    log_success "Restored: $restored files"
    [[ $failed -gt 0 ]] && log_error "Failed: $failed files"
    echo ""
    log_warning "REBOOT REQUIRED for all changes to take effect"

    return 0
}

#───────────────────────────────────────────────────────────────────────────────
# ZRAM CONFIGURATION
#───────────────────────────────────────────────────────────────────────────────

configure_zram() {
    log_subheader "Configuring ZRAM"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would create ZRAM config: ${ZRAM_SIZE_GB}GB, $ZRAM_ALGORITHM"
        return 0
    fi

    # Install zram-generator if needed
    if ! [[ -f /usr/lib/systemd/system-generators/zram-generator ]]; then
        log_info "Installing zram-generator..."
        case "$DISTRO_FAMILY" in
            redhat)
                dnf install -y zram-generator || {
                    add_anomaly "WARNING" "zram_install" "zram-generator" "not installed" \
                        "Could not install zram-generator" \
                        "Install manually: dnf install zram-generator"
                    return 1
                }
                ;;
            debian)
                apt-get update && apt-get install -y systemd-zram-generator || {
                    add_anomaly "WARNING" "zram_install" "systemd-zram-generator" "not installed" \
                        "Could not install zram-generator" \
                        "Install manually: apt install systemd-zram-generator"
                    return 1
                }
                ;;
            arch)
                pacman -S --noconfirm zram-generator || {
                    add_anomaly "WARNING" "zram_install" "zram-generator" "not installed" \
                        "Could not install zram-generator" \
                        "Install manually: pacman -S zram-generator"
                    return 1
                }
                ;;
            suse)
                zypper install -y zram-generator || {
                    add_anomaly "WARNING" "zram_install" "zram-generator" "not installed" \
                        "Could not install zram-generator" \
                        "Install manually: zypper install zram-generator"
                    return 1
                }
                ;;
            *)
                log_warning "Unknown distro family - please install zram-generator manually"
                return 1
                ;;
        esac
    fi

    # Create zram-generator config
    local zram_size_mb=$((ZRAM_SIZE_GB * 1024))

    cat > "$ZRAM_CONF" << EOF
# Universal Memory Optimizer - ZRAM Configuration
# Generated: $(date -Iseconds)
# Architecture: ZRAM = RAM/2 = ${ZRAM_SIZE_GB}GB

[zram0]
# Size in MB
zram-size = ${zram_size_mb}

# Compression algorithm
# zstd: Best compression ratio (~5:1), moderate CPU
# lz4: Fastest, lower compression (~2.5:1)
# lzo-rle: Good balance (kernel default since 5.1)
compression-algorithm = $ZRAM_ALGORITHM

# Swap priority (higher = preferred)
# ZRAM should be higher than disk swap
swap-priority = $ZRAM_PRIORITY

# File system (swap is most efficient for this use case)
fs-type = swap
EOF

    log_success "ZRAM config created: $ZRAM_CONF"

    # Reset ZRAM if device exists (required for zram-generator to reconfigure)
    if [[ -b /dev/zram0 ]]; then
        log_info "Resetting existing ZRAM device..."

        # Disable swap on ZRAM
        swapoff /dev/zram0 2>/dev/null || true

        # Reset the device completely (required before zram-generator can reconfigure)
        zramctl --reset /dev/zram0 2>/dev/null || true

        # Give kernel time to fully release the device
        sleep 0.5

        # Reload systemd to pick up new config
        systemctl daemon-reload

        # Start the service (not restart - device was reset)
        log_info "Starting ZRAM service with new config..."
        systemctl start systemd-zram-setup@zram0.service || {
            log_warning "zram-generator service failed, attempting manual setup..."

            # Cleanup any partial state
            swapoff /dev/zram0 2>/dev/null || true
            zramctl --reset /dev/zram0 2>/dev/null || true

            # Fallback: manual ZRAM setup
            modprobe zram num_devices=1 2>/dev/null || true
            echo "$ZRAM_ALGORITHM" > /sys/block/zram0/comp_algorithm 2>/dev/null || true
            echo $((ZRAM_SIZE_GB * 1024 * 1024 * 1024)) > /sys/block/zram0/disksize

            if ! mkswap /dev/zram0 >/dev/null 2>&1; then
                log_error "Failed to create swap on ZRAM device"
                add_anomaly "CRITICAL" "zram_mkswap" "/dev/zram0" "mkswap failed" \
                    "Could not format ZRAM device" \
                    "Check kernel logs: dmesg | grep zram"
                return 1
            fi

            if ! swapon -p $ZRAM_PRIORITY /dev/zram0 2>/dev/null; then
                log_error "Failed to activate ZRAM swap"
                add_anomaly "CRITICAL" "zram_swapon" "/dev/zram0" "swapon failed" \
                    "Could not activate ZRAM swap" \
                    "Check: swapon --show; dmesg | grep zram"
                return 1
            fi
            log_success "ZRAM configured manually with priority $ZRAM_PRIORITY"
        }
    else
        # No existing ZRAM, just start the service
        systemctl daemon-reload
        systemctl start systemd-zram-setup@zram0.service || {
            log_warning "zram-generator service failed"
        }
    fi

    # Verify ZRAM is active with correct priority
    if swapon --show | grep -q zram0; then
        local zram_prio=$(swapon --show=NAME,PRIO | grep zram0 | awk '{print $2}')
        if [[ "$zram_prio" -eq "$ZRAM_PRIORITY" ]]; then
            log_success "ZRAM active with priority $zram_prio"
        elif [[ "$zram_prio" -gt "$ZRAM_PRIORITY" ]]; then
            log_info "ZRAM priority is $zram_prio (higher than expected $ZRAM_PRIORITY, acceptable)"
        else
            log_warning "ZRAM priority is $zram_prio (expected $ZRAM_PRIORITY), attempting fix..."
            swapoff /dev/zram0 2>/dev/null || true
            if swapon -p $ZRAM_PRIORITY /dev/zram0 2>/dev/null; then
                # Verify the fix worked
                zram_prio=$(swapon --show=NAME,PRIO | grep zram0 | awk '{print $2}')
                if [[ "$zram_prio" -eq "$ZRAM_PRIORITY" ]]; then
                    log_success "ZRAM priority corrected to $ZRAM_PRIORITY"
                else
                    log_warning "ZRAM priority still $zram_prio after fix attempt"
                fi
            else
                log_error "Failed to reactivate ZRAM swap with priority $ZRAM_PRIORITY"
            fi
        fi
    fi

    return 0
}

#───────────────────────────────────────────────────────────────────────────────
# SWAPFILE CONFIGURATION
#───────────────────────────────────────────────────────────────────────────────

configure_swapfile() {
    log_subheader "Configuring Disk Swapfile"

    # Check hibernate protection
    if [[ "$HIBERNATE_STATUS" == "CONFIGURED" ]] && [[ "$FORCE_MODE" != "true" ]]; then
        log_warning "Hibernate swapfile detected - PRESERVING"
        log_info "Use --force to override (will break hibernate)"

        # Ensure swap is active
        if ! swapon --show | grep -q "$SWAPFILE_PATH"; then
            swapon "$SWAPFILE_PATH" 2>/dev/null || true
        fi
        return 0
    fi

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would create swapfile: ${SWAPFILE_SIZE_GB}GB at $SWAPFILE_PATH"
        return 0
    fi

    # Check if swapfile exists with correct size
    if [[ -f "$SWAPFILE_PATH" ]]; then
        local existing_bytes=$(stat -c%s "$SWAPFILE_PATH" 2>/dev/null || echo 0)
        local target_bytes=$((SWAPFILE_SIZE_GB * 1024 * 1024 * 1024))

        if [[ $existing_bytes -eq $target_bytes ]]; then
            log_info "Swapfile already exists with correct size (${SWAPFILE_SIZE_GB}GB)"

            # Ensure it's in fstab
            if ! grep -q "^$SWAPFILE_PATH" /etc/fstab; then
                echo "$SWAPFILE_PATH none swap sw,pri=$SWAPFILE_PRIORITY 0 0" >> /etc/fstab
                log_success "Added swapfile to fstab"
            fi

            # Ensure it's active
            if ! swapon --show | grep -q "$SWAPFILE_PATH"; then
                swapon "$SWAPFILE_PATH" && log_success "Activated swapfile"
            fi

            return 0
        fi

        log_info "Existing swapfile size mismatch, recreating..."
        swapoff "$SWAPFILE_PATH" 2>/dev/null || true
    fi

    # Create swapfile based on filesystem type
    log_info "Creating ${SWAPFILE_SIZE_GB}GB swapfile..."

    case "$ROOT_FS_TYPE" in
        btrfs)
            log_info "Btrfs detected - using special handling"
            # Remove existing file
            rm -f "$SWAPFILE_PATH"
            # Create empty file
            truncate -s 0 "$SWAPFILE_PATH"
            # Disable COW (required for btrfs swap)
            chattr +C "$SWAPFILE_PATH" 2>/dev/null || {
                log_warning "chattr +C failed - trying btrfs property"
            }
            # Disable compression
            btrfs property set "$SWAPFILE_PATH" compression none 2>/dev/null || true
            # Allocate space
            fallocate -l "${SWAPFILE_SIZE_GB}G" "$SWAPFILE_PATH" 2>/dev/null || \
                dd if=/dev/zero of="$SWAPFILE_PATH" bs=1G count="$SWAPFILE_SIZE_GB" status=progress
            ;;
        xfs|ext4)
            rm -f "$SWAPFILE_PATH"
            fallocate -l "${SWAPFILE_SIZE_GB}G" "$SWAPFILE_PATH" 2>/dev/null || \
                dd if=/dev/zero of="$SWAPFILE_PATH" bs=1G count="$SWAPFILE_SIZE_GB" status=progress
            ;;
        *)
            rm -f "$SWAPFILE_PATH"
            dd if=/dev/zero of="$SWAPFILE_PATH" bs=1G count="$SWAPFILE_SIZE_GB" status=progress
            ;;
    esac

    # Set permissions and format
    chmod 600 "$SWAPFILE_PATH"
    mkswap "$SWAPFILE_PATH" || {
        log_error "mkswap failed"
        return 1
    }

    # Add to fstab if not present
    if ! grep -q "^$SWAPFILE_PATH" /etc/fstab; then
        # Backup fstab
        cp /etc/fstab /etc/fstab.bak.$(date +%Y%m%d%H%M%S)
        echo "$SWAPFILE_PATH none swap sw,pri=$SWAPFILE_PRIORITY 0 0" >> /etc/fstab
        log_success "Added swapfile to fstab (priority $SWAPFILE_PRIORITY)"
    fi

    # Activate
    swapon "$SWAPFILE_PATH" && log_success "Swapfile activated (${SWAPFILE_SIZE_GB}GB)" || \
        log_warning "Swapfile activation failed - will activate on next boot"

    return 0
}

#───────────────────────────────────────────────────────────────────────────────
# SYSCTL CONFIGURATION
#───────────────────────────────────────────────────────────────────────────────

configure_sysctl() {
    log_subheader "Configuring Kernel Parameters"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would set sysctl parameters:"
        log_info "  vm.swappiness = $SYSCTL_SWAPPINESS"
        log_info "  vm.page-cluster = $SYSCTL_PAGE_CLUSTER"
        log_info "  vm.vfs_cache_pressure = $SYSCTL_VFS_CACHE_PRESSURE"
        return 0
    fi

    # Calculate min_free_kbytes based on RAM
    local min_free_kbytes
    if [[ $TOTAL_RAM_GB -le 4 ]]; then
        min_free_kbytes=65536      # 64MB
    elif [[ $TOTAL_RAM_GB -le 8 ]]; then
        min_free_kbytes=131072     # 128MB
    elif [[ $TOTAL_RAM_GB -le 16 ]]; then
        min_free_kbytes=262144     # 256MB
    else
        min_free_kbytes=524288     # 512MB
    fi

    cat > "$SYSCTL_CONF" << EOF
# Universal Memory Optimizer - Sysctl Configuration
# Generated: $(date -Iseconds)
#
# Best Practices Sources (2025-2026):
#   - ArchWiki: https://wiki.archlinux.org/title/Zram
#   - Kernel Docs: https://docs.kernel.org/admin-guide/sysctl/vm.html
#   - Pop!_OS defaults, ChromeOS, Android

#───────────────────────────────────────────────────────────────────────────────
# SWAP BEHAVIOR
#───────────────────────────────────────────────────────────────────────────────

# How aggressively to use swap (0-200)
# For ZRAM: 180 is optimal - swap to fast compressed RAM early
# Source: ArchWiki - "values beyond 100 can be considered for in-memory swap"
vm.swappiness = $SYSCTL_SWAPPINESS

# Pages to read at once from swap (2^n pages)
# 0 = single page - optimal for ZRAM (no prefetch needed)
# Source: ChromeOS, Android, Pop!_OS defaults
vm.page-cluster = $SYSCTL_PAGE_CLUSTER

#───────────────────────────────────────────────────────────────────────────────
# CACHE MANAGEMENT
#───────────────────────────────────────────────────────────────────────────────

# How aggressively to reclaim dentry/inode caches
# 50 = prefer keeping caches (good for responsiveness)
# Source: Kernel docs - "Decreasing causes kernel to prefer to retain caches"
vm.vfs_cache_pressure = $SYSCTL_VFS_CACHE_PRESSURE

#───────────────────────────────────────────────────────────────────────────────
# MEMORY WATERMARKS
#───────────────────────────────────────────────────────────────────────────────

# When to wake kswapd (fraction of 10000)
# 125 = wake kswapd earlier for smoother memory management
vm.watermark_scale_factor = $SYSCTL_WATERMARK_SCALE_FACTOR

# Disable watermark boosting (not needed with high swappiness)
vm.watermark_boost_factor = $SYSCTL_WATERMARK_BOOST_FACTOR

# Minimum free memory to keep
vm.min_free_kbytes = $min_free_kbytes

#───────────────────────────────────────────────────────────────────────────────
# DIRTY PAGE RATIOS
#───────────────────────────────────────────────────────────────────────────────

# When to start writeback (% of RAM)
vm.dirty_ratio = $SYSCTL_DIRTY_RATIO

# When to start background writeback (% of RAM)
vm.dirty_background_ratio = $SYSCTL_DIRTY_BACKGROUND_RATIO
EOF

    # Apply sysctl
    log_info "Applying sysctl parameters..."
    sysctl --system > /dev/null 2>&1

    log_success "Sysctl configuration applied"

    return 0
}

#───────────────────────────────────────────────────────────────────────────────
# ZSWAP DISABLE
#───────────────────────────────────────────────────────────────────────────────

disable_zswap() {
    log_subheader "Disabling ZSWAP"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would disable ZSWAP via $DETECTED_BOOTLOADER"
        return 0
    fi

    # Disable at runtime
    if [[ -f /sys/module/zswap/parameters/enabled ]]; then
        echo 0 > /sys/module/zswap/parameters/enabled 2>/dev/null && \
            log_success "ZSWAP disabled at runtime" || \
            log_info "ZSWAP runtime disable failed (will be disabled after reboot)"
    fi

    # Disable in bootloader
    case "$DETECTED_BOOTLOADER" in
        grub)
            if command -v grubby &>/dev/null; then
                grubby --update-kernel=ALL --args="zswap.enabled=0" && \
                    log_success "ZSWAP disabled in GRUB" || \
                    log_warning "grubby command failed"
            else
                log_warning "grubby not found - add 'zswap.enabled=0' to kernel cmdline manually"
            fi
            ;;

        systemd-boot)
            local cmdline_file="/etc/kernel/cmdline"
            if ! grep -q "zswap.enabled=0" "$cmdline_file" 2>/dev/null; then
                if [[ -f "$cmdline_file" ]]; then
                    sed -i 's/$/ zswap.enabled=0/' "$cmdline_file"
                else
                    cat /proc/cmdline | sed 's/BOOT_IMAGE=[^ ]* //' > "$cmdline_file"
                    echo " zswap.enabled=0" >> "$cmdline_file"
                fi

                if command -v kernel-install &>/dev/null; then
                    kernel-install add "$(uname -r)" "/lib/modules/$(uname -r)/vmlinuz" && \
                        log_success "ZSWAP disabled in systemd-boot" || \
                        log_warning "kernel-install failed"
                fi
            else
                log_info "ZSWAP already disabled in cmdline"
            fi
            ;;

        uki)
            log_warning "UKI detected - add 'zswap.enabled=0' to /etc/kernel/cmdline"
            log_warning "Then rebuild UKI: dracut --force --uefi"

            local cmdline_file="/etc/kernel/cmdline"
            if ! grep -q "zswap.enabled=0" "$cmdline_file" 2>/dev/null; then
                echo "zswap.enabled=0" >> "$cmdline_file"
                log_info "Added zswap.enabled=0 to $cmdline_file (rebuild required)"
            fi
            ;;

        *)
            log_warning "Unknown bootloader - add 'zswap.enabled=0' to kernel cmdline manually"
            ;;
    esac

    return 0
}

# NOTE: OOM policy removed - trusting kernel default OOM killer
# 3-tier system (RAM → ZRAM → Swapfile → Kernel OOM) is sufficient
# Never-kill policy removed to prevent deadlocks

#───────────────────────────────────────────────────────────────────────────────
# VERIFICATION SCRIPT
#───────────────────────────────────────────────────────────────────────────────

create_verification_script() {
    log_subheader "Creating Verification Script"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would create verification script at $VERIFY_SCRIPT"
        return 0
    fi

    cat > "$VERIFY_SCRIPT" << 'VERIFY_EOF'
#!/bin/bash
#═══════════════════════════════════════════════════════════════════════════════
# Universal Memory Optimizer - Verification Script
# Run after reboot to verify configuration
#═══════════════════════════════════════════════════════════════════════════════

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

echo ""
echo -e "${CYAN}═══════════════════════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}Universal Memory Optimizer - Verification Report${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════════════════════${NC}"
echo ""

check_value() {
    local name="$1"
    local expected="$2"
    local actual="$3"

    if [[ "$actual" == "$expected" ]]; then
        echo -e "  ${GREEN}✓${NC} $name = $actual"
        return 0
    else
        echo -e "  ${YELLOW}⚠${NC} $name = $actual (expected: $expected)"
        return 1
    fi
}

# 1. ZRAM Status
echo -e "${BOLD}1. ZRAM Status${NC}"
if zramctl 2>/dev/null | grep -q zram0; then
    echo -e "  ${GREEN}✓ ZRAM is active${NC}"
    zramctl --output NAME,ALGORITHM,DISKSIZE,DATA,COMPR,TOTAL | head -2 | sed 's/^/   /'

    comp_algo=$(cat /sys/block/zram0/comp_algorithm 2>/dev/null | grep -o '\[.*\]' | tr -d '[]')
    echo "   Algorithm: ${comp_algo:-unknown}"
else
    echo -e "  ${RED}✗ ZRAM is NOT active${NC}"
fi
echo ""

# 2. Swap Configuration
echo -e "${BOLD}2. Swap Configuration${NC}"
swapon --show 2>/dev/null | sed 's/^/   /' || echo "   No swap active"
echo ""

# 3. Kernel Parameters
echo -e "${BOLD}3. Kernel Parameters${NC}"
check_value "vm.swappiness" "180" "$(cat /proc/sys/vm/swappiness)"
check_value "vm.page-cluster" "0" "$(cat /proc/sys/vm/page_cluster 2>/dev/null || echo "N/A")"
check_value "vm.vfs_cache_pressure" "50" "$(cat /proc/sys/vm/vfs_cache_pressure)"
check_value "vm.watermark_scale_factor" "125" "$(cat /proc/sys/vm/watermark_scale_factor)"
echo ""

# 4. ZSWAP Status
echo -e "${BOLD}4. ZSWAP Status${NC}"
if [[ -f /sys/module/zswap/parameters/enabled ]]; then
    zswap_enabled=$(cat /sys/module/zswap/parameters/enabled)
    if [[ "$zswap_enabled" == "N" ]] || [[ "$zswap_enabled" == "0" ]]; then
        echo -e "  ${GREEN}✓ ZSWAP is disabled${NC}"
    else
        echo -e "  ${YELLOW}⚠ ZSWAP is enabled (should be disabled for ZRAM)${NC}"
    fi
else
    echo -e "  ${GREEN}✓ ZSWAP module not loaded${NC}"
fi
echo ""

# 5. Memory Status
echo -e "${BOLD}5. Current Memory Status${NC}"
free -h | sed 's/^/   /'
echo ""

# 6. Memory Pressure (PSI)
if [[ -f /proc/pressure/memory ]]; then
    echo -e "${BOLD}6. Memory Pressure (PSI)${NC}"
    cat /proc/pressure/memory | sed 's/^/   /'
    echo ""
fi

# Summary
echo -e "${CYAN}═══════════════════════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}Verification Complete${NC}"
echo -e "${CYAN}═══════════════════════════════════════════════════════════════════════${NC}"
echo ""
VERIFY_EOF

    chmod +x "$VERIFY_SCRIPT"
    log_success "Verification script created: $VERIFY_SCRIPT"

    return 0
}

#───────────────────────────────────────────────────────────────────────────────
# DIAGNOSTIC REPORT
#───────────────────────────────────────────────────────────────────────────────

generate_report() {
    log_subheader "Generating Diagnostic Report"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would generate report at $REPORT_DIR/report-YYYYMMDD-HHMMSS.json"
        return 0
    fi

    mkdir -p "$REPORT_DIR"
    local report_file="$REPORT_DIR/report-$(date +%Y%m%d-%H%M%S).json"

    cat > "$report_file" << EOF
{
    "version": "$SCRIPT_VERSION",
    "generated": "$(date -Iseconds)",
    "system": {
        "hostname": "$(hostname)",
        "kernel": "$(uname -r)",
        "distro": "$DISTRO",
        "distro_family": "$DISTRO_FAMILY",
        "distro_version": "$DISTRO_VERSION",
        "init_system": "$INIT_SYSTEM",
        "bootloader": "$DETECTED_BOOTLOADER",
        "bootloader_confidence": "$BOOTLOADER_CONFIDENCE",
        "root_fs_type": "$ROOT_FS_TYPE"
    },
    "memory": {
        "total_ram_gb": $TOTAL_RAM_GB,
        "zram_size_gb": $ZRAM_SIZE_GB,
        "swapfile_size_gb": $SWAPFILE_SIZE_GB,
        "architecture": "ZRAM=RAM/2, Swapfile=ZRAM/2"
    },
    "configuration": {
        "zram_algorithm": "$ZRAM_ALGORITHM",
        "sysctl": {
            "swappiness": $SYSCTL_SWAPPINESS,
            "page_cluster": $SYSCTL_PAGE_CLUSTER,
            "vfs_cache_pressure": $SYSCTL_VFS_CACHE_PRESSURE,
            "watermark_scale_factor": $SYSCTL_WATERMARK_SCALE_FACTOR
        }
    },
    "hibernate": {
        "status": "$HIBERNATE_STATUS",
        "swapfile_size_gb": $HIBERNATE_SWAPFILE_SIZE
    },
    "backup_dir": "$CURRENT_BACKUP_DIR",
    "anomalies": [
        $(IFS=,; echo "${ANOMALIES[*]:-}")
    ],
    "warnings": $(printf '%s\n' "${WARNINGS[@]:-}" | jq -R . | jq -s .),
    "successes": $(printf '%s\n' "${SUCCESSES[@]:-}" | jq -R . | jq -s .)
}
EOF

    log_success "Report saved: $report_file"

    return 0
}

#───────────────────────────────────────────────────────────────────────────────
# SUMMARY
#───────────────────────────────────────────────────────────────────────────────

print_summary() {
    log_header "Installation Summary"

    echo ""
    echo -e "${BOLD}System:${NC}"
    echo "  Distro: $DISTRO v$DISTRO_VERSION"
    echo "  RAM: ${TOTAL_RAM_GB}GB"
    echo "  Bootloader: $DETECTED_BOOTLOADER ($BOOTLOADER_CONFIDENCE)"
    echo ""

    echo -e "${BOLD}Configuration:${NC}"
    echo "  ZRAM: ${ZRAM_SIZE_GB}GB (${ZRAM_RATIO}% of RAM) @ priority $ZRAM_PRIORITY"
    echo "  Swapfile: ${SWAPFILE_SIZE_GB}GB (${SWAPFILE_RATIO}% of RAM) @ priority $SWAPFILE_PRIORITY"
    echo "  Compression: $ZRAM_ALGORITHM"
    echo ""

    echo -e "${BOLD}Kernel Parameters:${NC}"
    echo "  vm.swappiness = $SYSCTL_SWAPPINESS"
    echo "  vm.page-cluster = $SYSCTL_PAGE_CLUSTER"
    echo "  vm.vfs_cache_pressure = $SYSCTL_VFS_CACHE_PRESSURE"
    echo ""

    if [[ ${#SUCCESSES[@]} -gt 0 ]]; then
        echo -e "${BOLD}${GREEN}Completed:${NC}"
        for s in "${SUCCESSES[@]}"; do
            echo "  ✓ $s"
        done
        echo ""
    fi

    if [[ ${#WARNINGS[@]} -gt 0 ]]; then
        echo -e "${BOLD}${YELLOW}Warnings:${NC}"
        for w in "${WARNINGS[@]}"; do
            echo "  ⚠ $w"
        done
        echo ""
    fi

    echo -e "${BOLD}Backup:${NC} $CURRENT_BACKUP_DIR"
    echo ""

    echo -e "${YELLOW}════════════════════════════════════════════════════════════════════${NC}"
    echo -e "${BOLD}${YELLOW}  ⚠  REBOOT REQUIRED for all changes to take effect${NC}"
    echo -e "${YELLOW}════════════════════════════════════════════════════════════════════${NC}"
    echo ""
    echo "After reboot, run: ${BOLD}memory-optimizer-verify${NC}"
    echo ""
}

#───────────────────────────────────────────────────────────────────────────────
# HELP
#───────────────────────────────────────────────────────────────────────────────

show_help() {
    cat << EOF
${BOLD}Universal Memory Optimizer v$SCRIPT_VERSION${NC}

Cross-distribution Linux memory optimizer with ZRAM + Disk Swap
Architecture: ZRAM = RAM/2, Swapfile = ZRAM/2

${BOLD}USAGE:${NC}
    $0 [OPTIONS]

${BOLD}OPTIONS:${NC}
    --dry-run           Show what would be done without making changes
    --force             Force operations (override hibernate protection)
    --verbose           Enable verbose output
    --yes               Skip confirmation prompts
    --rollback PATH     Rollback to a previous backup
    --list-backups      List available backups
    --verify            Run verification checks only
    --help              Show this help message
    --version           Show version

${BOLD}EXAMPLES:${NC}
    # Standard installation
    sudo $0

    # Dry-run to see what would happen
    sudo $0 --dry-run

    # Force install even with hibernate configured
    sudo $0 --force

    # Rollback to previous configuration
    sudo $0 --rollback /root/memory-optimizer-backups/backup-20260127-123456

${BOLD}ARCHITECTURE:${NC}
    3-tier swap system (trusts kernel OOM as last resort):

    Example for 32GB RAM:
      ZRAM:     16GB (RAM/2) - compressed, priority 100
      Swapfile:  8GB (ZRAM/2) - disk, priority 10

    Memory pressure flow:
      RAM → ZRAM (fast, compressed) → Disk (slower) → Kernel OOM

${BOLD}FILES:${NC}
    $SYSCTL_CONF        - Kernel parameters
    $ZRAM_CONF           - ZRAM configuration
    $SWAPFILE_PATH       - Disk swapfile
    $BACKUP_BASE/        - Backups
    $VERIFY_SCRIPT       - Verification script

${BOLD}SOURCES:${NC}
    - ArchWiki ZRAM: https://wiki.archlinux.org/title/Zram
    - Kernel Docs: https://docs.kernel.org/admin-guide/sysctl/vm.html
    - Fedora Changes: https://fedoraproject.org/wiki/Changes/SwapOnZRAM

EOF
}

#───────────────────────────────────────────────────────────────────────────────
# MAIN
#───────────────────────────────────────────────────────────────────────────────

main() {
    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --dry-run)
                DRY_RUN=true
                ;;
            --force)
                FORCE_MODE=true
                ;;
            --verbose|-v)
                VERBOSE=true
                ;;
            --yes|-y)
                SKIP_CONFIRMATION=true
                ;;
            --rollback)
                [[ $EUID -ne 0 ]] && { log_error "Root privileges required"; exit 1; }
                rollback "${2:-}"
                exit $?
                ;;
            --list-backups)
                list_backups
                exit 0
                ;;
            --verify)
                [[ -x "$VERIFY_SCRIPT" ]] && exec "$VERIFY_SCRIPT"
                log_error "Verification script not found: $VERIFY_SCRIPT"
                exit 1
                ;;
            --help|-h)
                show_help
                exit 0
                ;;
            --version)
                echo "$SCRIPT_VERSION"
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                show_help
                exit 1
                ;;
        esac
        shift
    done

    # Header
    echo ""
    echo -e "${CYAN}═══════════════════════════════════════════════════════════════════════${NC}"
    echo -e "${BOLD}  Universal Memory Optimizer v$SCRIPT_VERSION${NC}"
    echo -e "${CYAN}═══════════════════════════════════════════════════════════════════════${NC}"
    echo ""
    echo "  Architecture: ZRAM = RAM/2, Swapfile = ZRAM/2"
    echo "  OOM: Kernel default (3-tier swap approach)"
    [[ "$DRY_RUN" == "true" ]] && echo -e "  ${YELLOW}DRY-RUN MODE - No changes will be made${NC}"
    echo ""

    # Root check
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi

    # System detection
    detect_system || exit 1

    # Pre-flight checks
    preflight_checks || exit 1

    # Confirmation
    if [[ "$SKIP_CONFIRMATION" != "true" ]] && [[ "$DRY_RUN" != "true" ]]; then
        echo ""
        echo -e "${BOLD}This will:${NC}"
        echo "  1. Create backup of current configuration"
        echo "  2. Configure ZRAM: ${ZRAM_SIZE_GB}GB with $ZRAM_ALGORITHM compression"
        echo "  3. Configure swapfile: ${SWAPFILE_SIZE_GB}GB at $SWAPFILE_PATH"
        echo "  4. Set kernel parameters for optimal ZRAM performance"
        echo "  5. Disable ZSWAP (conflicts with ZRAM)"
        echo ""

        read -r -p "Proceed with installation? (y/N) " response
        if [[ ! "$response" =~ ^[Yy] ]]; then
            log_info "Installation cancelled"
            exit 0
        fi
    fi

    # Create backup
    create_backup

    # Configure components
    configure_zram || log_warning "ZRAM configuration failed"
    configure_swapfile || log_warning "Swapfile configuration failed"
    configure_sysctl || log_warning "Sysctl configuration failed"
    disable_zswap || log_warning "ZSWAP disable failed"
    create_verification_script || log_warning "Verification script creation failed"

    # Generate report
    generate_report || log_warning "Report generation failed"

    # Summary
    print_summary

    return 0
}

# Run
main "$@"
