#!/bin/bash
#═══════════════════════════════════════════════════════════════════════════════
# OOM POLICY FUNCTIONS
# To be sourced by memory-optimizer.sh
#
# Provides:
#   - configure_oom_policy(): Main entry point
#   - install_oom_daemon(): Installs the OOM protection daemon
#   - configure_earlyoom(): Configures earlyoom preferences
#   - configure_systemd_oomd(): Configures systemd-oomd
#   - configure_slice_limits(): Sets up cgroup memory limits
#
# Author: Generated by Claude (Anthropic)
# License: MIT
# Version: 1.0.0
#═══════════════════════════════════════════════════════════════════════════════

#───────────────────────────────────────────────────────────────────────────────
# OOM POLICY CONSTANTS
#───────────────────────────────────────────────────────────────────────────────

readonly OOM_DAEMON_SCRIPT="/usr/local/bin/oom-protection-daemon"
readonly OOM_DAEMON_SERVICE="/etc/systemd/system/oom-protection-daemon.service"
readonly EARLYOOM_CONF="/etc/default/earlyoom"
readonly OOMD_CONF_DIR="/etc/systemd/oomd.conf.d"
readonly USER_SLICE_CONF_DIR="/etc/systemd/system/user-.slice.d"
readonly SYSTEM_SLICE_CONF_DIR="/etc/systemd/system/system.slice.d"

# Memory allocation (for 16GB RAM example)
# System reserved: ~1-2GB
# User apps max: ~14GB
readonly SYSTEM_MEMORY_RESERVE_PERCENT=12  # 12% of RAM reserved for system
readonly USER_MEMORY_HIGH_PERCENT=80       # Throttle at 80%
readonly USER_MEMORY_MAX_PERCENT=87        # Hard limit at 87%

#───────────────────────────────────────────────────────────────────────────────
# INSTALL OOM PROTECTION DAEMON
#───────────────────────────────────────────────────────────────────────────────

install_oom_daemon() {
    log_subheader "Installing OOM Protection Daemon"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would install OOM protection daemon"
        return 0
    fi

    # Create the daemon script
    cat > "$OOM_DAEMON_SCRIPT" << 'DAEMON_EOF'
#!/bin/bash
#═══════════════════════════════════════════════════════════════════════════════
# OOM PROTECTION DAEMON - Inline version
# Sets oom_score_adj based on process categories
#═══════════════════════════════════════════════════════════════════════════════

set -euo pipefail

readonly LOG_FILE="/var/log/oom-protection-daemon.log"
readonly PID_FILE="/run/oom-protection-daemon.pid"
SCAN_INTERVAL=${SCAN_INTERVAL:-5}

# OOM Score values
readonly SCORE_IMMORTAL=-1000
readonly SCORE_PROTECTED=-900
readonly SCORE_KILLABLE=500

# Process patterns (simplified for inline)
IMMORTAL_REGEX="^(gnome-shell|mutter|gsd-|gnome-session|gnome-keyring|Xorg|Xwayland|gdm|pipewire|wireplumber|pulseaudio|systemd|dbus|polkit|NetworkManager|bluetoothd|evolution-|goa-|tracker-|gjs|at-spi|gvfs|dconf|colord|udisksd|upowerd)$"
PROTECTED_REGEX="^(code|code-insiders|vscodium|idea|pycharm|webstorm|goland|clion|sublime_text|vim|nvim|emacs|gnome-terminal|alacritty|kitty|tilix|konsole|nautilus|dolphin|thunar|docker|podman)$"
KILLABLE_REGEX="^(firefox|chrome|chromium|google-chrome|brave|opera|vivaldi|edge|epiphany|midori|WebKit|slack|Slack|discord|Discord|teams|zoom|skype|telegram|signal|element)$"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" >> "$LOG_FILE"
}

get_comm() { cat "/proc/$1/comm" 2>/dev/null || echo ""; }
get_score() { cat "/proc/$1/oom_score_adj" 2>/dev/null || echo ""; }

set_score() {
    local pid="$1" score="$2" name="$3"
    if [[ -w "/proc/$pid/oom_score_adj" ]]; then
        echo "$score" > "/proc/$pid/oom_score_adj" 2>/dev/null && \
            log "Set $name (PID $pid) -> $score"
    fi
}

categorize() {
    local name="$1"
    if [[ "$name" =~ $IMMORTAL_REGEX ]]; then echo "IMMORTAL"
    elif [[ "$name" =~ $PROTECTED_REGEX ]]; then echo "PROTECTED"
    elif [[ "$name" =~ $KILLABLE_REGEX ]]; then echo "KILLABLE"
    else echo "NORMAL"
    fi
}

get_target_score() {
    case "$1" in
        IMMORTAL)  echo "$SCORE_IMMORTAL" ;;
        PROTECTED) echo "$SCORE_PROTECTED" ;;
        KILLABLE)  echo "$SCORE_KILLABLE" ;;
        *)         echo "0" ;;
    esac
}

scan_processes() {
    for pid_dir in /proc/[0-9]*; do
        local pid=$(basename "$pid_dir")
        [[ ! -s "/proc/$pid/cmdline" ]] && continue

        local name=$(get_comm "$pid")
        [[ -z "$name" ]] && continue

        local current=$(get_score "$pid")
        [[ -z "$current" ]] && continue

        local category=$(categorize "$name")
        local target=$(get_target_score "$category")

        # Only update if needed
        if [[ "$category" == "IMMORTAL" && "$current" != "$target" ]] || \
           [[ "$category" == "PROTECTED" && "$current" -gt "$SCORE_PROTECTED" ]] || \
           [[ "$category" == "KILLABLE" && "$current" -lt "$SCORE_KILLABLE" ]]; then
            set_score "$pid" "$target" "$name"
        fi
    done
}

start_daemon() {
    [[ -f "$PID_FILE" ]] && kill -0 "$(cat "$PID_FILE")" 2>/dev/null && exit 1
    mkdir -p "$(dirname "$LOG_FILE")"
    echo $$ > "$PID_FILE"
    trap 'rm -f "$PID_FILE"; exit 0' SIGTERM SIGINT
    log "OOM Protection Daemon started"
    while true; do scan_processes; sleep "$SCAN_INTERVAL"; done
}

run_once() {
    scan_processes
    echo "Scan complete. Key processes:"
    for proc in gnome-shell mutter pipewire code firefox chrome; do
        for pid in $(pgrep "$proc" 2>/dev/null | head -2); do
            printf "  %-20s PID %-6s Score: %s\n" "$(get_comm "$pid")" "$pid" "$(get_score "$pid")"
        done
    done
}

status() {
    echo "OOM Protection Status"
    echo "====================="
    local im=0 pr=0 ki=0
    for pid_dir in /proc/[0-9]*; do
        local pid=$(basename "$pid_dir")
        [[ ! -s "/proc/$pid/cmdline" ]] && continue
        local score=$(get_score "$pid")
        [[ -z "$score" ]] && continue
        [[ "$score" -le -1000 ]] && ((im++))
        [[ "$score" -le -500 && "$score" -gt -1000 ]] && ((pr++))
        [[ "$score" -ge 500 ]] && ((ki++))
    done
    echo "  IMMORTAL:  $im"
    echo "  PROTECTED: $pr"
    echo "  KILLABLE:  $ki"
}

case "${1:-}" in
    start)    [[ $EUID -ne 0 ]] && exit 1; start_daemon ;;
    run-once) [[ $EUID -ne 0 ]] && exit 1; run_once ;;
    status)   status ;;
    *)        echo "Usage: $0 {start|run-once|status}" ;;
esac
DAEMON_EOF

    chmod +x "$OOM_DAEMON_SCRIPT"
    log_success "OOM daemon script installed: $OOM_DAEMON_SCRIPT"

    # Create systemd service
    cat > "$OOM_DAEMON_SERVICE" << 'SERVICE_EOF'
[Unit]
Description=OOM Protection Daemon
After=multi-user.target graphical.target
Wants=graphical.target

[Service]
Type=simple
ExecStart=/usr/local/bin/oom-protection-daemon start
Restart=on-failure
RestartSec=5
MemoryMax=50M
CPUQuota=5%
OOMScoreAdjust=-1000
OOMPolicy=continue

[Install]
WantedBy=multi-user.target
SERVICE_EOF

    log_success "OOM daemon service installed: $OOM_DAEMON_SERVICE"

    # Enable and start the service
    systemctl daemon-reload
    systemctl enable oom-protection-daemon.service
    systemctl start oom-protection-daemon.service || log_warning "Could not start daemon (might need reboot)"

    log_success "OOM Protection Daemon installed and enabled"
    return 0
}

#───────────────────────────────────────────────────────────────────────────────
# CONFIGURE EARLYOOM
#───────────────────────────────────────────────────────────────────────────────

configure_earlyoom() {
    log_subheader "Configuring earlyoom"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would configure earlyoom"
        return 0
    fi

    # Check if earlyoom is installed
    if ! command -v earlyoom &>/dev/null && ! systemctl list-unit-files | grep -q earlyoom; then
        log_info "earlyoom not installed, skipping"
        return 0
    fi

    # Backup existing config
    [[ -f "$EARLYOOM_CONF" ]] && cp "$EARLYOOM_CONF" "${EARLYOOM_CONF}.backup.$(date +%Y%m%d)"

    cat > "$EARLYOOM_CONF" << 'EARLYOOM_EOF'
# Fedora Memory Optimizer - earlyoom Configuration
# ================================================
# Kill browsers FIRST, protect system and IDEs

EARLYOOM_ARGS="\
-r 60 \
-m 5 \
-s 90 \
--prefer '^(firefox|firefox-esr|chrome|chromium|google-chrome|brave|brave-browser|opera|vivaldi|microsoft-edge|epiphany|midori|WebKitWebProcess|slack|Slack|discord|Discord|teams|zoom|skypeforlinux|telegram-desktop|signal-desktop|element-desktop)$' \
--avoid '^(gnome-shell|mutter|gsd-.*|gnome-session.*|gnome-keyring.*|Xorg|Xwayland|gdm.*|pipewire|pipewire-pulse|wireplumber|pulseaudio|systemd|dbus-daemon|dbus-broker|polkitd|NetworkManager|bluetoothd|code|code-insiders|vscodium|idea.*|pycharm.*|webstorm.*|goland.*|clion.*|sublime_text|vim|nvim|emacs.*|gnome-terminal.*|alacritty|kitty|tilix|nautilus|dolphin)$' \
-n \
--avoid-oom-score-adj \
"
EARLYOOM_EOF

    # Restart earlyoom
    systemctl restart earlyoom 2>/dev/null || log_warning "Could not restart earlyoom"

    log_success "earlyoom configured"
    return 0
}

#───────────────────────────────────────────────────────────────────────────────
# CONFIGURE SYSTEMD-OOMD
#───────────────────────────────────────────────────────────────────────────────

configure_systemd_oomd() {
    log_subheader "Configuring systemd-oomd (passive backup)"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would configure systemd-oomd"
        return 0
    fi

    mkdir -p "$OOMD_CONF_DIR"

    # Remove any conflicting configs
    rm -f "$OOMD_CONF_DIR/99-aggressive.conf" 2>/dev/null

    cat > "$OOMD_CONF_DIR/99-memory-optimizer.conf" << 'OOMD_EOF'
# Fedora Memory Optimizer - systemd-oomd Configuration
# PASSIVE BACKUP to earlyoom

[OOM]
SwapUsedLimit=95%
DefaultMemoryPressureLimit=80%
DefaultMemoryPressureDurationSec=60s
OOMD_EOF

    systemctl restart systemd-oomd 2>/dev/null || log_warning "Could not restart systemd-oomd"

    log_success "systemd-oomd configured (passive mode)"
    return 0
}

#───────────────────────────────────────────────────────────────────────────────
# CONFIGURE SLICE MEMORY LIMITS
#───────────────────────────────────────────────────────────────────────────────

configure_slice_limits() {
    log_subheader "Configuring cgroup memory limits"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY-RUN] Would configure slice memory limits"
        log_info "[DRY-RUN] User slice: MemoryHigh=${USER_MEMORY_HIGH_PERCENT}%, MemoryMax=${USER_MEMORY_MAX_PERCENT}%"
        return 0
    fi

    # User slice configuration
    mkdir -p "$USER_SLICE_CONF_DIR"
    cat > "$USER_SLICE_CONF_DIR/50-memory-limit.conf" << SLICE_EOF
# Fedora Memory Optimizer - User Slice Memory Limits
# Generated: $(date -Iseconds)

[Slice]
MemoryHigh=${USER_MEMORY_HIGH_PERCENT}%
MemoryMax=${USER_MEMORY_MAX_PERCENT}%
MemorySwapMax=infinity
ManagedOOMSwap=kill
ManagedOOMMemoryPressure=kill
ManagedOOMMemoryPressureLimit=80%
SLICE_EOF

    log_success "User slice configured: MemoryHigh=${USER_MEMORY_HIGH_PERCENT}%, MemoryMax=${USER_MEMORY_MAX_PERCENT}%"

    # System slice protection
    mkdir -p "$SYSTEM_SLICE_CONF_DIR"
    cat > "$SYSTEM_SLICE_CONF_DIR/50-memory-protection.conf" << SLICE_EOF
# Fedora Memory Optimizer - System Slice Protection
# Generated: $(date -Iseconds)

[Slice]
MemoryLow=1G
ManagedOOMPreference=avoid
SLICE_EOF

    log_success "System slice protected: MemoryLow=1G"

    systemctl daemon-reload

    return 0
}

#───────────────────────────────────────────────────────────────────────────────
# MAIN OOM POLICY FUNCTION
#───────────────────────────────────────────────────────────────────────────────

configure_oom_policy() {
    local policy="${1:-hybrid}"

    log_header "Configuring OOM Policy: $policy"

    case "$policy" in
        never-kill)
            log_info "Never-kill policy: System may freeze under extreme pressure"
            log_info "Processes will be throttled but NEVER killed"

            # Disable earlyoom
            systemctl disable --now earlyoom 2>/dev/null || true

            # Configure oomd with very high thresholds
            mkdir -p "$OOMD_CONF_DIR"
            cat > "$OOMD_CONF_DIR/99-memory-optimizer.conf" << EOF
[OOM]
SwapUsedLimit=99%
DefaultMemoryPressureLimit=95%
DefaultMemoryPressureDurationSec=120s
EOF
            systemctl restart systemd-oomd 2>/dev/null || true

            # Install daemon
            install_oom_daemon

            # Configure slices (no hard limit)
            mkdir -p "$USER_SLICE_CONF_DIR"
            cat > "$USER_SLICE_CONF_DIR/50-memory-limit.conf" << EOF
[Slice]
MemoryHigh=90%
MemoryMax=infinity
ManagedOOMSwap=auto
EOF
            systemctl daemon-reload

            log_success "Never-kill policy configured"
            ;;

        hybrid)
            log_info "Hybrid policy: Protect system & IDEs, kill browsers first"

            # Install daemon
            install_oom_daemon

            # Configure earlyoom
            configure_earlyoom

            # Configure oomd as backup
            configure_systemd_oomd

            # Configure slice limits
            configure_slice_limits

            log_success "Hybrid OOM policy configured"
            ;;

        passive)
            log_info "Passive policy: systemd-oomd only with high thresholds"

            # Disable earlyoom
            systemctl disable --now earlyoom 2>/dev/null || true

            # Configure oomd
            configure_systemd_oomd

            log_success "Passive OOM policy configured"
            ;;

        active)
            log_info "Active policy: Aggressive OOM for maximum responsiveness"

            # Enable earlyoom with lower thresholds
            configure_earlyoom

            # Configure oomd with lower thresholds
            mkdir -p "$OOMD_CONF_DIR"
            cat > "$OOMD_CONF_DIR/99-memory-optimizer.conf" << EOF
[OOM]
SwapUsedLimit=80%
DefaultMemoryPressureLimit=60%
DefaultMemoryPressureDurationSec=20s
EOF
            systemctl restart systemd-oomd 2>/dev/null || true

            log_success "Active OOM policy configured"
            ;;

        *)
            log_error "Unknown OOM policy: $policy"
            log_info "Available policies: never-kill, hybrid, passive, active"
            return 1
            ;;
    esac

    # Show summary
    echo ""
    log_info "OOM Policy Summary:"
    echo "  Policy:          $policy"
    echo "  earlyoom:        $(systemctl is-enabled earlyoom 2>/dev/null || echo 'not installed')"
    echo "  systemd-oomd:    $(systemctl is-enabled systemd-oomd 2>/dev/null || echo 'not installed')"
    echo "  OOM daemon:      $(systemctl is-enabled oom-protection-daemon 2>/dev/null || echo 'not installed')"

    return 0
}

#───────────────────────────────────────────────────────────────────────────────
# EXPORT FUNCTIONS (for sourcing)
#───────────────────────────────────────────────────────────────────────────────

# If run directly (not sourced), show help
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "OOM Policy Functions for Fedora Memory Optimizer"
    echo ""
    echo "This script should be sourced by memory-optimizer.sh"
    echo "Or run with: sudo bash -c 'source $0; configure_oom_policy hybrid'"
    echo ""
    echo "Available functions:"
    echo "  configure_oom_policy <policy>  - Main entry point"
    echo "  install_oom_daemon             - Install OOM protection daemon"
    echo "  configure_earlyoom             - Configure earlyoom"
    echo "  configure_systemd_oomd         - Configure systemd-oomd"
    echo "  configure_slice_limits         - Configure cgroup limits"
    echo ""
    echo "Policies: never-kill, hybrid, passive, active"
fi
